"use client";

import React, { useState } from "react";
import { Compass, Rocket, AlertTriangle, CheckCircle2 } from "lucide-react";
import LatexMath from "../LatexMath";
// Single source of truth: the archived table generated by src/targets.py.
// Editing numbers here would desynchronise the site from results/targets.json,
// so every value below is read from the archive (including the bounded ranges,
// which are assumption ranges — A in [0.15, 0.45] times a ±15% radius
// allowance — not propagated catalogue uncertainties).
import TARGET_ARCHIVE from "../../results/targets.json";

interface ArchiveTarget {
  name: string;
  host: string;
  spt: string;
  d_pc: number;
  msini: number;
  P_d: number;
  S: number;
  ecc: number;
  Rp_nominal_R: number;
  Rp_terr_1sigma_R: number;
  above_ck_transition: boolean;
  Dimg_km: number;
  pix64_m: number;
  SNRC_nominal: number;
  SNRC_rule_bounded: [number, number];
  foc_ra_h: number;
  foc_dec_d: number;
  foc_ecl_lat: number;
  v_img_ms: number;
  dv90_face_on_kms: number;
  dv90_face_on_range_kms: [number, number];
  dv90_edge_on_kms: number;
  note: string;
}

const TARGETS: ArchiveTarget[] = TARGET_ARCHIVE.targets as unknown as ArchiveTarget[];

const LY_PER_PC = 3.26156;

export default function TargetCatalogExplorer() {
  const [selectedName, setSelectedName] = useState<string>("Ross 128 b");
  const target = TARGETS.find((t) => t.name === selectedName) || TARGETS[0];
  const refuted = /refuted/i.test(target.note);
  const snrLo = target.SNRC_rule_bounded[0];
  const snrHi = target.SNRC_rule_bounded[1];
  const dvLo = target.dv90_face_on_range_kms[0];
  const dvHi = target.dv90_face_on_range_kms[1];

  return (
    <div className="card">
      <div className="card-header flex items-center justify-between flex-wrap gap-2">
        <div className="flex items-center gap-2">
          <div className="badge badge-primary flex items-center gap-1">
            <Compass size={14} />
            <span>Exoplanet Target Database</span>
          </div>
          <h3 className="text-lg font-bold text-slate-800">
            Target Catalog &amp; Focal-Line Tracking Dynamics
          </h3>
        </div>
        <span className="text-xs text-slate-500 font-mono text-right">
          5 confirmed + 1 illustrative row, z = 650 AU, d = 1 m, λ = 1 μm
        </span>
      </div>

      <div className="card-body space-y-4">
        <div className="flex items-start gap-2 p-2.5 bg-amber-50 border border-amber-200 rounded-lg text-[11px] text-amber-900 leading-snug">
          <AlertTriangle size={14} className="mt-0.5 shrink-0 text-amber-600" />
          <span>
            This is a <strong>nominal-proxy table</strong>, not an uncertainty budget and not a
            site-selection study. Ranges are bounded products of the stated albedo
            (A ∈ [0.15, 0.45]) and radius allowance (±15%); they are assumptions, not
            confidence intervals. Values come from <code>results/targets.json</code>.
          </span>
        </div>

        {/* Target Buttons */}
        <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-6 gap-2 mb-1">
          {TARGETS.map((t) => (
            <button
              key={t.name}
              onClick={() => setSelectedName(t.name)}
              className={`p-2.5 rounded-lg text-left border transition-all ${
                selectedName === t.name
                  ? "border-blue-600 bg-blue-50/70 shadow-sm"
                  : "border-slate-200 hover:border-slate-300 bg-white"
              }`}
            >
              <div className="text-xs font-bold text-slate-800 truncate">{t.name}</div>
              <div className="text-[11px] text-slate-500">{(t.d_pc * LY_PER_PC).toFixed(1)} ly</div>
              <div className="text-[10px] font-mono text-blue-600 mt-1">
                {t.Dimg_km.toFixed(1)} km img
              </div>
              {/refuted/i.test(t.note) && (
                <div className="text-[9px] font-bold text-rose-600 mt-0.5">illustrative only</div>
              )}
            </button>
          ))}
        </div>

        {/* Selected Target Deep Dive */}
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-4 items-start">
          {/* Main Info Card */}
          <div className="bg-slate-50 p-4 rounded-xl border border-slate-200 space-y-3">
            <div className="flex justify-between items-start">
              <div>
                <h4 className="text-base font-bold text-slate-900">{target.name}</h4>
                <div className="text-xs text-slate-500">
                  {target.host} ({target.spt})
                </div>
              </div>
              <span className="badge badge-accent text-xs">
                {target.d_pc.toFixed(2)} pc ({(target.d_pc * LY_PER_PC).toFixed(1)} ly)
              </span>
            </div>

            <div
              className={`p-2.5 rounded-lg border text-xs space-y-1 ${
                refuted
                  ? "bg-rose-50 border-rose-200"
                  : "bg-emerald-50 border-emerald-200"
              }`}
            >
              <span
                className={`font-bold flex items-center gap-1 ${
                  refuted ? "text-rose-900" : "text-emerald-900"
                }`}
              >
                {refuted ? (
                  <AlertTriangle size={13} className="text-rose-600" />
                ) : (
                  <CheckCircle2 size={13} className="text-emerald-600" />
                )}
                {refuted ? "Status:" : "Archive note:"}
              </span>
              <p className={refuted ? "text-rose-800 leading-snug" : "text-emerald-800 leading-snug"}>
                {target.note}
              </p>
            </div>

            <div className="pt-2 border-t border-slate-200 text-xs space-y-1.5 font-mono">
              <div className="flex justify-between text-slate-600">
                <span>Orbital Period:</span>
                <span className="font-bold text-slate-800">{target.P_d.toFixed(2)} days</span>
              </div>
              <div className="flex justify-between text-slate-600">
                <span>Eccentricity:</span>
                <span className="font-bold text-slate-800">{target.ecc.toFixed(2)}</span>
              </div>
              <div className="flex justify-between text-slate-600">
                <span>Insolation:</span>
                <span className="font-bold text-slate-800">{target.S.toFixed(2)} S⊕</span>
              </div>
              <div className="flex justify-between text-slate-600">
                <span>M sin i:</span>
                <span className="font-bold text-slate-800">{target.msini.toFixed(2)} M⊕</span>
              </div>
              <div className="flex justify-between text-slate-600">
                <span>R_p (Chen &amp; Kipping):</span>
                <span className="font-bold text-slate-800">
                  {target.Rp_nominal_R.toFixed(2)} ± {target.Rp_terr_1sigma_R.toFixed(2)} R⊕
                </span>
              </div>
              <div className="flex justify-between text-slate-600">
                <span>Focal direction (J2000):</span>
                <span className="font-bold text-slate-800">
                  {target.foc_ra_h.toFixed(2)}ʰ, {target.foc_dec_d > 0 ? "+" : ""}
                  {target.foc_dec_d.toFixed(1)}°
                </span>
              </div>
              <div className="flex justify-between text-slate-600">
                <span>Focal β_ecl:</span>
                <span className="font-bold text-slate-800">
                  {target.foc_ecl_lat > 0 ? "+" : ""}
                  {target.foc_ecl_lat.toFixed(1)}°
                </span>
              </div>
            </div>

            {target.above_ck_transition && (
              <p className="text-[10px] text-slate-500 leading-snug">
                M sin i lies above the Chen &amp; Kipping (2017) Terran/Neptunian transition
                (2.04 M⊕), so the rocky-branch radius used here is an extrapolation, not a
                measurement.
              </p>
            )}
          </div>

          {/* SGL Focal Image & Optical Parameters */}
          <div className="bg-slate-50 p-4 rounded-xl border border-slate-200 space-y-3">
            <h4 className="text-xs font-bold uppercase tracking-wider text-slate-600">
              SGL Focal Image Characteristics (at 650 AU)
            </h4>

            <div className="bg-white p-3 rounded-lg border border-slate-200 space-y-1">
              <div className="text-xs text-slate-500">Projected Image Plane Diameter</div>
              <div className="text-2xl font-bold font-mono text-slate-900">
                {target.Dimg_km.toFixed(1)} <span className="text-sm font-normal">km</span>
              </div>
              <div className="text-[11px] text-slate-400">
                <LatexMath math="D_{\rm img} = 2 R_p\,(z/z_0)" />; 64-pixel raster pitch{" "}
                {target.pix64_m.toFixed(0)} m
              </div>
            </div>

            <div className="bg-white p-3 rounded-lg border border-slate-200 space-y-1">
              <div className="text-xs text-slate-500">Per-Sample SNR (1800 s Dwell, 1 m)</div>
              <div className="text-2xl font-bold font-mono text-blue-600">
                <LatexMath math="\mathrm{SNR_C} \simeq" /> {target.SNRC_nominal.toFixed(0)}
              </div>
              <div className="text-[11px] text-slate-400">
                Bounded range [{snrLo.toFixed(0)}–{snrHi.toFixed(0)}] over A ∈ [0.15, 0.45] and a
                ±15% radius allowance — an assumption range, not a confidence interval.
              </div>
            </div>

            <div className="bg-white p-3 rounded-lg border border-slate-200 space-y-1">
              <div className="text-xs text-slate-500">Focal Image Linear Velocity</div>
              <div className="text-xl font-bold font-mono text-slate-800">
                {target.v_img_ms.toFixed(1)} <span className="text-xs font-normal">m/s</span>
              </div>
              <div className="text-[11px] text-slate-400">
                Speed at which the planetary image sweeps across the image plane.
              </div>
            </div>
          </div>

          {/* Tracking Requirement */}
          <div className="bg-slate-50 p-4 rounded-xl border border-slate-200 space-y-3">
            <h4 className="text-xs font-bold uppercase tracking-wider text-slate-600">
              90-Day Focal-Track Requirement
            </h4>

            <div className="bg-white p-3.5 rounded-lg border border-slate-200 space-y-2">
              <div className="flex items-center justify-between">
                <span className="text-xs text-slate-500">Tracking Δv over 90 days (face-on)</span>
                <Rocket size={16} className="text-amber-600" />
              </div>
              <div className="text-2xl font-bold font-mono text-amber-600">
                {target.dv90_face_on_kms.toFixed(2)}{" "}
                <span className="text-sm font-normal">km/s</span>
              </div>
              <div className="text-[11px] text-slate-500 leading-snug">
                Range over starting mean anomaly in the window: [{dvLo.toFixed(2)}–
                {dvHi.toFixed(2)}] km/s. Edge-on value: {target.dv90_edge_on_kms.toFixed(2)} km/s
                (ratio 2/π = 0.6366).
              </div>
              <p className="text-[11px] text-slate-500 leading-snug">
                Computed as <LatexMath math="\Delta v(T) = \oint |\mathbf{a}_\perp(t)|\,dt" /> over
                the projected Keplerian transverse acceleration, not the circular estimate. As the
                planet orbits, its focal cylinder drifts; the fleet must steer to stay inside it.
              </p>
            </div>

            {/* Scale Comparison Bar */}
            <div className="bg-white p-3 rounded-lg border border-slate-200 space-y-2">
              <div className="text-xs font-semibold text-slate-700">Relative Tracking Difficulty:</div>
              <div className="w-full bg-slate-100 h-2.5 rounded-full overflow-hidden">
                <div
                  className={`h-full rounded-full ${
                    target.dv90_face_on_kms > 4
                      ? "bg-rose-500"
                      : target.dv90_face_on_kms > 2
                      ? "bg-amber-500"
                      : "bg-emerald-500"
                  }`}
                  style={{ width: `${Math.min(100, (target.dv90_face_on_kms / 6.0) * 100)}%` }}
                />
              </div>
              <div className="flex justify-between text-[10px] font-mono text-slate-400">
                <span>GJ 273 b: 1.34 km/s (lowest confirmed)</span>
                <span>Prox b: 5.81 km/s (highest)</span>
              </div>
            </div>

            <div className="p-2.5 bg-blue-50/60 rounded border border-blue-100 text-[11px] text-blue-900 leading-snug">
              <strong>Scope note:</strong> the paper produces this Δv requirement only. Propulsion
              sizing, plane-change cost for high |β_ecl| rows, and formation keeping are trajectory
              work it explicitly does not attempt.
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
